### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by Melanie-M** [manzonif/apollo-upload-angular-link-http#1]
After using `yarn add apollo-upload-angular-link-http`, the package is installed in `node-modules` and I import it in `app.module.ts` like so:

     import {HttpLink} from 'apollo-upload-angular-link-http';

When building, I get:

> ERROR in src/app/app.module.ts(23,24): error TS2307: Cannot find module 'apollo-upload-angular-link-http'.

It use to work fine, I think it broke with the last commit. Maybe it wasn't published to npm correctly ? As a workaround I have copied the files locally and import from there, and it works.

**Comment by manzonif** [comment]
@Melanie-M  sould be fixed now. Thanks.
